CREATE TABLE receipt (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	username VARCHAR(30),
	file varchar(70),
	category varchar(10),
	payment varchar(10)
	);
	
CREATE TABLE user (
	username VARCHAR(30) PRIMARY KEY,
	password VARCHAR(100),
	enabled INTEGER
	);
	
CREATE TABLE user_roles (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	username VARCHAR(30),
	roleID INTEGER
	);
	
CREATE TABLE roles (
	roleID INTEGER PRIMARY KEY,
	role varchar(6)
	);